name: Deploy Clone Bot to Heroku via Github Workflows (US Region)

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_telegram_token: ${{secrets.TELEGRAM_TOKEN}}
          HD_user_ids: ${{secrets.USER_IDS}}
          HD_group_ids: ${{secrets.GROUP_IDS}}
